/*
* generated by Xtext
*/
package org.cmg.tapas.rm.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ModuleStandaloneSetup extends ModuleStandaloneSetupGenerated{

	public static void doSetup() {
		new ModuleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

