/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.clts.validation

import org.cmg.tapas.xtext.clts.composedLts.Lts
import org.eclipse.xtext.validation.Check
import static extension org.eclipse.xtext.EcoreUtil2.*
import org.cmg.tapas.xtext.clts.composedLts.Model
import org.cmg.tapas.xtext.clts.composedLts.ComposedLtsPackage
import org.cmg.tapas.xtext.clts.composedLts.Reference

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ComposedLtsValidator extends AbstractComposedLtsValidator {
	public static final String DUPLICATED_LTS_NAME = "DUPLICATED_LTS_NAME"
	
	public static final String LTS_NOT_DEFINED = "LTS_NOT_DEFINED"
	
	@Check
	def checkSingleLtsName( Lts lts ){
		var model = lts.getContainerOfType(typeof(Model));
		var withName = model.elements.filter(typeof(Lts)).filter[ it.name == lts.name]
		if(withName.size > 1) {
			error( 'Duplicated lts name' , ComposedLtsPackage.Literals.ELEMENT__NAME , DUPLICATED_LTS_NAME)
		}
	}
	
	@Check
	def checkLtsNotDefined( Reference ref ){
		var lts = ref.getContainerOfType(typeof(Lts))
		var ltsName = lts.name
		if(lts.name == ref.lts.name){
			error( 'Lts not defined yet' , ComposedLtsPackage.Literals.REFERENCE__LTS, LTS_NOT_DEFINED)
		}
	}
}
