/**
 * generated by Xtext
 */
package org.cmg.tapas.xtext.ccsp.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class CCSPSpecificationQuickfixProvider extends DefaultQuickfixProvider {
}
