/*
 * generated by Xtext
 */
package org.cmg.tapas.rm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModuleUiModule extends org.cmg.tapas.rm.xtext.ui.AbstractModuleUiModule {
	public ModuleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
