/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.slts;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleLtsRuntimeModule extends org.cmg.tapas.xtext.slts.AbstractSimpleLtsRuntimeModule {

//    // this is required only by the CompilationTestHelper since Xtext 2.7
//    public Class<? extends org.eclipse.xtend.lib.macro.file.MutableFileSystemSupport> bindMutableFileSystemSupport() {
//        return org.eclipse.xtext.xbase.file.JavaIOFileSystemSupport.class;
//    }
//
//    // this is required only by the CompilationTestHelper since Xtext 2.7
//    public Class<? extends com.google.inject.Provider<org.eclipse.xtext.xbase.file.WorkspaceConfig>> provideWorkspaceConfig() {
//        return org.eclipse.xtext.xbase.file.RuntimeWorkspaceConfigProvider.class;
//    }
    
}
