/*
* generated by Xtext
*/
package org.cmg.tapas.xtext.slts;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SimpleLtsStandaloneSetup extends SimpleLtsStandaloneSetupGenerated{

	public static void doSetup() {
		new SimpleLtsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

