/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.slts.ui.contentassist

import org.cmg.tapas.xtext.slts.ui.contentassist.AbstractSimpleLtsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SimpleLtsProposalProvider extends AbstractSimpleLtsProposalProvider {
}
