/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.ccsp.ui.contentassist

import org.cmg.tapas.xtext.ccsp.ui.contentassist.AbstractCCSPSpecificationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CCSPSpecificationProposalProvider extends AbstractCCSPSpecificationProposalProvider {
}
