/*
 * generated by Xtext
 */
package org.lic.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.lic.secsi.Assignment;
import org.lic.secsi.Program;
import org.lic.secsi.Statement;

import com.google.inject.Inject;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class SecsiScopeProvider extends AbstractDeclarativeScopeProvider {
	
	@Inject
	ActiveSymbolCollector collector;

	IScope scope_ReferenceInExpression_reference(Program p , EReference ref) {
	//	System.out.println("ORA?");
		return IScope.NULLSCOPE;
	}


	IScope scope_ReferenceInExpression_reference(Statement s , EReference ref) {
	//	System.out.println("HERE!!!!");
		return collector.getActiveSymbol(s);
	}
	
	IScope scope_Assignment_id( Assignment s , EReference ref ) {
	//	System.out.println("AND HERE!!!!");
		return collector.getActiveSymbol(s);
	}
}