/*
 * generated by Xtext
 */
package org.lic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SecsiUiModule extends org.lic.ui.AbstractSecsiUiModule {
	public SecsiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
