/*
 * generated by Xtext
 */
package org.cmg.tapas.rm.xtext.ui.contentassist

import org.cmg.tapas.rm.xtext.ui.contentassist.AbstractModuleProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ModuleProposalProvider extends AbstractModuleProposalProvider {
}
