/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.ccsp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CCSPSpecificationUiModule extends org.cmg.tapas.xtext.ccsp.ui.AbstractCCSPSpecificationUiModule {
	public CCSPSpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return org.cmg.tapas.xtext.ccsp.ui.wizard.CustomCCSPSpecificationProjectCreator.class;
	}
}
