/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.clts.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ComposedLtsUiModule extends org.cmg.tapas.xtext.clts.ui.AbstractComposedLtsUiModule {
	public ComposedLtsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return org.cmg.tapas.xtext.clts.ui.wizard.CustomComposedLtsProjectCreator.class;
	}
}
