/*
* generated by Xtext
*/
package org.cmg.tapas.xtext.clts;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ComposedLtsStandaloneSetup extends ComposedLtsStandaloneSetupGenerated{

	public static void doSetup() {
		new ComposedLtsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

