/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.clts;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComposedLtsRuntimeModule extends org.cmg.tapas.xtext.clts.AbstractComposedLtsRuntimeModule {

}
