/*
* generated by Xtext
*/
package org.lic.ui.contentassist;

import org.lic.ui.contentassist.AbstractSecsiProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SecsiProposalProvider extends AbstractSecsiProposalProvider {

}
