/*
 * generated by Xtext
 */
package org.cmg.tapas.xtext.clts.ui.contentassist

import org.cmg.tapas.xtext.clts.ui.contentassist.AbstractComposedLtsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ComposedLtsProposalProvider extends AbstractComposedLtsProposalProvider {
}
